
version: "3.8"

services:
  django:
    build: .
    container_name: ww_django

    ports:
      - "8000:8000"
      
    command: ["sh", "./run.sh"]

    depends_on:
      - pgdb
      - rabit

  pgdb:
    image: postgres:14.1-alpine
    
    container_name: ww_pgdb
    healthcheck:
      #test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

    environment:
       - POSTGRES_USER=henry
       - POSTGRES_PASSWORD=henry
       - POSTGRES_DB=wisdomise

    ports:
       - "5432:5432"

  pg_admin:
    image: "dpage/pgadmin4:latest"
    container_name: ww_pgadmin
    
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"
  
  rabit:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFUALT_USER=guest
      - RABBITMQ_DEFUALT_PASS=guest

  zookeeper:
    image: zookeeper:latest
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper"
      KAFKA_CREATE_TOPICS: "wisdomise_broker:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock




